package com.javix.wordflipster


val twoLetterWords = listOf(
    "ad", "am", "an", "as", "at", "be", "by", "do", "go", "he",
    "hi", "if", "in", "is", "it", "me", "my", "no", "of", "on",
    "or", "so", "to", "up", "us", "we", "ax", "ex", "ye", "oh",
    "ow", "pi", "xi", "id", "ma", "ha", "ho", "bi", "ab", "ah",
    "ai", "al", "ba", "bo", "da", "de", "ed", "ef", "eh", "el",
    "em", "en", "er", "et", "fa", "go", "ha", "ho", "la", "li",
    "lo", "mu", "na", "ne", "nu", "od", "oe", "oi", "op", "pa",
    "pe", "re", "ta", "uh", "um", "un", "ut", "ya", "yo", "za",
    "aa", "ab", "ad", "ae", "ag", "ah", "ai", "al", "am", "an",
    "ar", "as", "at", "aw", "ax", "ay", "ba", "bi", "bo", "da",
    "de", "di", "do", "ed", "ef", "eh", "el", "em", "en", "er",
    "es", "et", "ex", "fa", "go", "ha", "hi", "ho", "id", "if",
    "in", "is", "it", "jo", "ka", "la", "li", "lo", "ma", "me",
    "mi", "mu", "my", "na", "no", "nu", "od", "oe", "of", "oh",
    "oi", "om", "on", "op", "or", "os", "ow", "ox", "pa", "pe",
    "pi", "re", "sh", "si", "so", "ta", "ti", "to", "uh", "um",
    "un", "up", "us", "ut", "we", "wo", "xi", "ye", "yo", "za",
    "aa", "ae", "ba", "bi", "bo", "da", "do", "ed", "ef", "eh",
    "el", "em", "en", "er", "es", "et", "ex", "go", "ho", "id",
    "if", "in", "is", "it", "jo", "ka", "la", "li", "lo", "ma",
    "me", "mi", "mu", "my", "na", "no", "od", "oe", "of", "oh",
    "oi", "om", "on", "op", "or", "os", "ow", "ox", "pa", "pe",
    "pi", "re", "sh", "si", "so", "ta", "to", "uh", "um", "un",
    "up", "us", "ut", "we", "wo", "ye", "yo", "za", "al", "ad",
    "am", "ar", "as", "at", "be", "by", "do", "go", "he", "hi",
    "if", "me", "my", "no", "of", "on", "or", "so", "to", "up",
    "ax", "ex", "ye", "oh", "ow", "pi", "xi", "ma", "ha", "ho",
    "bi", "ab", "ah", "ai", "al", "ba", "bo", "de", "ed", "ef",
    "el", "em", "en", "er", "et", "fa", "go", "ha", "ho", "la",
    "li", "lo", "mu", "na", "ne", "nu", "pa", "pe", "re", "ta",
    "uh", "um", "un", "ut", "ya", "yo", "za", "ah", "ai", "al",
    "am", "an", "ar", "as", "at", "aw", "ax", "ay", "ba", "bi",
    "bo", "da", "de", "do", "ed", "eh", "el", "em", "en", "er",
    "es", "et", "ex", "fa", "go", "ha", "hi", "ho", "id", "if",
    "in", "is", "it", "ka", "la", "li", "ma", "me", "mi", "my",
    "no", "nu", "od", "oe", "of", "oh", "oi", "om", "on", "op",
    "or", "os", "ow", "ox", "pa", "pe", "pi", "re", "sh", "si",
    "so", "ta", "to", "uh", "um", "un", "up", "us", "ut", "we",
    "wo", "xi", "yo", "za"
)

val threeLetterWords = listOf(
    "and", "the", "for", "are", "but", "you", "not", "all", "any", "can",
    "had", "his", "her", "was", "one", "out", "day", "man", "see", "too",
    "new", "use", "how", "say", "get", "who", "let", "if", "now", "way",
    "map", "bed", "big", "cat", "dog", "egg", "fan", "gas", "hat", "jar",
    "kid", "log", "man", "nap", "pen", "rat", "sun", "tap", "van", "win",
    "zip", "ape", "bat", "cap", "dip", "ear", "fan", "gem", "hog", "ink",
    "jot", "kit", "lip", "mud", "nut", "owl", "pig", "red", "sky", "tin",
    "urn", "vet", "wok", "yak", "zoo", "axe", "bay", "cob", "die", "eel",
    "fig", "gas", "ham", "ivy", "jet", "keg", "lip", "mop", "net", "oak",
    "pie", "rat", "sip", "toe", "van", "wax", "yew", "zip", "but", "add",
    "age", "ask", "bar", "bid", "bow", "buy", "cog", "cue", "dig", "dub",
    "dry", "eon", "fan", "fry", "gag", "gap", "gel", "guy", "hew", "ill",
    "jib", "jog", "lab", "law", "led", "lip", "log", "mat", "mug", "nab",
    "nap", "pat", "pay", "pet", "pop", "rat", "run", "set", "sow", "spy",
    "tap", "tip", "ton", "van", "vat", "web", "win", "yet", "zip", "ace",
    "add", "ale", "ant", "ash", "axe", "bad", "bee", "bop", "box", "bun",
    "cab", "cat", "con", "cow", "cry", "cub", "cut", "dam", "dye", "ear",
    "eel", "end", "fan", "fix", "fog", "fun", "gap", "gas", "gel", "get",
    "ham", "hot", "ill", "jam", "jar", "joy", "kin", "lap", "lip", "mud",
    "nap", "new", "oak", "opt", "pat", "pen", "pet", "pop", "pot", "ram",
    "red", "rib", "rug", "sad", "sea", "sip", "tan", "tap", "toe", "tub",
    "vet", "war", "web", "wig", "yap", "yay", "zap", "ape", "bat", "cap",
    "day", "ear", "fan", "gas", "hat", "jar", "kid", "log", "man", "nap",
    "pen", "rat", "sun", "tap", "van", "win", "zip", "art", "ash", "bar",
    "bat", "bop", "bot", "but", "can", "cat", "dig", "due", "ear", "fry",
    "gal", "gas", "hit", "job", "lab", "lap", "lip", "map", "mud", "net",
    "oak", "pea", "pet", "pot", "red", "run", "sat", "sow", "tap", "tie",
    "tip", "toe", "ton", "van", "vow", "war", "wet", "yak", "zip", "zoo",
    "age", "air", "ale", "ant", "ape", "arc", "ash", "ask", "bag", "bat",
    "bee", "big", "bow", "cat", "cob", "cup", "dog", "dot", "dry", "fan",
    "far", "fox", "fun", "gap", "gem", "ham", "hat", "hit", "hot", "ice",
    "jam", "jet", "kin", "kit", "lap", "lid", "log", "map", "mix", "nap",
    "net", "oak", "off", "opt", "owl", "pad", "pen", "pet", "pop", "pot",
    "pun", "rat", "red", "rib", "row", "run", "set", "tag", "tea", "tie",
    "tip", "toe", "ton", "van", "vow", "wag", "wax", "wet", "yap", "yet",
    "zip", "zoo", "abs", "add", "ala", "ale", "and", "apt", "arc", "aye",
    "bed", "bop", "bow", "cry", "dew", "dig", "dot", "ear", "eel", "elf",
    "fry", "fob", "few", "fur", "get", "had", "hem", "hey", "hut", "jam",
    "kit", "lad", "lay", "log", "mad", "mat", "mix", "nap", "net", "nod",
    "oak", "opt", "pad", "pig", "pot", "red", "run", "sat", "sow", "tap",
    "tie", "ton", "van", "vow", "wag", "wax", "wet", "yap", "yet", "zip",
    "zoo", "air", "age", "ale", "and", "ant", "ape", "arc", "ash", "ask",
    "bag", "bat", "bee", "big", "bow", "cat", "cob", "cup", "dog", "dot",
    "dry", "fan", "far", "fox", "fun", "gap", "gem", "ham", "hat", "hit",
    "hot", "ice", "jam", "jet", "kin", "kit", "lap", "lid", "log", "map",
    "mud", "net", "oak", "off", "opt", "owl", "pad", "pen", "pet", "pop",
    "pot", "pun", "rat", "red", "rib", "row", "run", "set", "tag", "tea",
    "tie", "tip", "toe", "ton", "van", "vow", "wag", "wax", "wet", "yap",
    "yet", "zip", "zoo", "abs", "add", "ala", "ale", "and", "apt", "arc",
    "aye", "bed", "bop", "bow", "cry", "dew", "dig", "dot", "ear", "eel",
    "elf", "fry", "fob", "few", "fur", "get", "had", "hem", "hey", "hut",
    "jam", "kit", "lad", "lay", "log", "mad", "mat", "mix", "nap", "net",
    "nod", "oak", "opt", "pad", "pig", "pot", "red", "run", "sat", "sow",
    "tap", "tie", "ton", "van", "vow", "wag", "wax", "wet", "yap", "yet",
    "zip", "zoo", "abs", "add", "ala", "ale", "and", "apt", "arc", "aye",
    "bed", "bop", "bow", "cry", "dew", "dig", "dot", "ear", "eel", "elf",
    "fry", "fob", "few", "fur", "get", "had", "hem", "hey", "hut", "jam",
    "kit", "lad", "lay", "log", "mad", "mat", "mix", "nap", "net", "nod",
    "oak", "opt", "pad", "pig", "pot", "red", "run", "sat", "sow", "tap",
    "tie", "ton", "van", "vow", "wag", "wax", "wet", "yap", "yet", "zip"
)

val fourLetterWords = listOf(
    "able", "acid", "aged", "also", "area", "army", "away", "baby", "back", "ball",
    "band", "bank", "base", "bath", "bear", "beat", "been", "beer", "bell", "belt",
    "best", "bill", "bird", "blow", "blue", "boat", "body", "bomb", "bond", "bone",
    "book", "boom", "born", "boss", "both", "bowl", "bulk", "burn", "bush", "busy",
    "call", "calm", "came", "camp", "card", "care", "case", "cash", "cast", "cell",
    "chat", "chip", "city", "club", "coal", "coat", "code", "cold", "come", "cook",
    "cool", "cope", "copy", "core", "cost", "crew", "crop", "dark", "data", "date",
    "dawn", "days", "dead", "deal", "dean", "dear", "debt", "deep", "deny", "desk",
    "dial", "diet", "disk", "does", "done", "door", "dose", "down", "draw", "drop",
    "drug", "dual", "duke", "dust", "duty", "each", "earn", "ease", "east", "easy",
    "edge", "else", "even", "ever", "evil", "exit", "face", "fact", "fail", "fair",
    "fall", "farm", "fast", "fate", "fear", "feed", "feel", "feet", "fell", "felt",
    "file", "fill", "film", "find", "fine", "fire", "firm", "fish", "five", "flat",
    "flow", "food", "foot", "form", "fort", "four", "free", "from", "fuel", "full",
    "fund", "gain", "game", "gate", "gave", "gear", "gene", "gift", "girl", "give",
    "glad", "goal", "goes", "gold", "golf", "gone", "good", "gray", "grew", "grow",
    "gulf", "hair", "half", "hall", "hand", "hang", "hard", "harm", "hate", "have",
    "head", "hear", "heat", "held", "help", "here", "hero", "high", "hill", "hire",
    "hold", "hole", "holy", "home", "hope", "host", "hour", "huge", "hung", "hunt",
    "hurt", "idea", "inch", "into", "iron", "item", "jack", "jane", "jean", "john",
    "join", "jump", "jury", "just", "keen", "keep", "kent", "kept", "kill", "kind",
    "king", "knee", "knew", "know", "lack", "lady", "laid", "lake", "land", "lane",
    "last", "late", "lead", "left", "less", "life", "lift", "like", "line", "link",
    "list", "live", "load", "loan", "lock", "logo", "long", "look", "lord", "lose",
    "loss", "lost", "love", "luck", "made", "mail", "main", "make", "male", "many",
    "mark", "mass", "matt", "meal", "mean", "meat", "meet", "menu", "mere", "mike",
    "mile", "milk", "mind", "mine", "miss", "mode", "mood", "moon", "more", "most",
    "move", "much", "must", "name", "navy", "near", "neck", "need", "news", "next",
    "nice", "nick", "nine", "none", "nose", "note", "okay", "once", "only", "onto",
    "open", "oral", "over", "pace", "pack", "page", "pain", "pair", "palm", "park",
    "part", "pass", "past", "path", "peak", "pick", "pink", "pipe", "plan", "play",
    "plot", "plug", "plus", "poll", "pool", "poor", "port", "post", "pull", "pure",
    "push", "race", "rail", "rain", "rank", "rare", "rate", "read", "real", "rear",
    "rely", "rent", "rest", "rice", "rich", "ride", "ring", "rise", "risk", "road",
    "rock", "role", "roll", "roof", "room", "root", "rose", "rule", "rush", "safe",
    "said", "sake", "sale", "salt", "same", "sand", "save", "seat", "seed", "seek",
    "seem", "seen", "sell", "send", "sept", "ship", "shop", "shot", "show", "shut",
    "sick", "side", "sign", "site", "size", "skin", "slip", "slow", "snow", "soft",
    "soil", "sold", "sole", "some", "song", "soon", "sort", "soul", "spot", "star",
    "stay", "step", "stop", "such", "suit", "sure", "take", "talk", "tall", "tank",
    "tape", "task", "team", "tell", "tend", "term", "test", "text", "than", "that",
    "them", "then", "they", "thin", "this", "thus", "time", "tiny", "told", "toll",
    "tone", "tony", "took", "tool", "tour", "town", "tree", "trip", "true", "tune",
    "turn", "type", "unit", "upon", "used", "user", "vary", "vast", "very", "vice",
    "view", "vote", "wage", "wait", "wake", "walk", "wall", "want", "ward", "warm",
    "wash", "wave", "ways", "weak", "wear", "week", "well", "went", "were", "west",
    "what", "when", "whom", "wide", "wife", "wild", "will", "wind", "wine", "wing",
    "wire", "wise", "wish", "with", "wood", "word", "wore", "work", "yard", "yeah",
    "year", "your", "zero", "zone", "able", "acid", "aged", "also", "area", "army",
    "away", "baby", "back", "ball", "band", "bank", "base", "bath", "bear", "beat",
    "been", "beer", "bell", "belt", "best", "bill", "bird", "blow", "blue", "boat",
    "body", "bomb", "bond", "bone", "book", "boom", "born", "boss", "both", "bowl",
    "bulk", "burn", "bush", "busy", "call", "calm", "came", "camp", "card", "care",
    "case", "cash", "cast", "cell", "chat", "chip", "city", "club", "coal", "coat",
    "code", "cold", "come", "cook", "cool", "cope", "copy", "core", "cost", "crew",
    "crop", "dark", "data", "date", "dawn", "days", "dead", "deal", "dean", "dear",
    "debt", "deep", "deny", "desk", "dial", "diet", "disk", "does", "done", "door",
    "dose", "down", "draw", "drop", "drug", "dual", "duke", "dust", "duty", "each",
    "earn", "ease", "east", "easy", "edge", "else", "even", "ever", "evil", "exit",
    "face", "fact", "fail", "fair", "fall", "farm", "fast", "fate", "fear", "feed",
    "feel", "feet", "fell", "felt", "file", "fill", "film", "find", "fine", "fire",
    "firm", "fish", "five", "flat", "flow", "food", "foot", "form", "fort", "four"
)

val fiveLetterWords = listOf(
    "about", "above", "abuse", "actor", "acute", "admit", "adopt", "adult", "after", "again",
    "agent", "agree", "ahead", "alarm", "album", "alert", "alike", "alive", "allow", "alone",
    "along", "alter", "among", "anger", "angle", "angry", "apart", "apple", "apply", "arena",
    "argue", "arise", "array", "aside", "asset", "audio", "audit", "avoid", "award", "aware",
    "badly", "baker", "bases", "basic", "basis", "beach", "began", "begin", "begun", "being",
    "below", "bench", "billy", "birth", "black", "blame", "blind", "block", "blood", "board",
    "boost", "booth", "bound", "brain", "brand", "bread", "break", "breed", "brief", "bring",
    "broad", "broke", "brown", "build", "built", "buyer", "cable", "calif", "carry", "catch",
    "cause", "chain", "chair", "chart", "chase", "cheap", "check", "chest", "chief", "child",
    "china", "chose", "civil", "claim", "class", "clean", "clear", "click", "clock", "close",
    "coach", "coast", "could", "count", "court", "cover", "craft", "crash", "cream", "crime",
    "cross", "crowd", "crown", "curve", "cycle", "daily", "dance", "dated", "dealt", "death",
    "debut", "delay", "depth", "doing", "doubt", "dozen", "draft", "drama", "drawn", "dream",
    "dress", "drill", "drink", "drive", "drove", "dying", "eager", "early", "earth", "eight",
    "elite", "empty", "enemy", "enjoy", "enter", "entry", "equal", "error", "event", "every",
    "exact", "exist", "extra", "faith", "false", "fault", "fiber", "field", "fifth", "fifty",
    "fight", "final", "first", "fixed", "flash", "fleet", "flesh", "floor", "fluid", "focus",
    "force", "forth", "forty", "forum", "found", "frame", "frank", "fraud", "fresh", "front",
    "fruit", "fully", "funny", "giant", "given", "glass", "globe", "going", "grace", "grade",
    "grand", "grant", "grass", "great", "green", "gross", "group", "grown", "guard", "guess",
    "guest", "guide", "happy", "harry", "heart", "heavy", "hence", "henry", "horse", "hotel",
    "house", "human", "ideal", "image", "imply", "index", "inner", "input", "issue", "japan",
    "jimmy", "joint", "jones", "judge", "known", "label", "large", "laser", "later", "laugh",
    "layer", "learn", "lease", "least", "leave", "legal", "level", "lewis", "light", "limit",
    "links", "lives", "local", "logic", "loose", "lower", "lucky", "lunch", "lying", "magic",
    "major", "maker", "march", "maria", "match", "maybe", "mayor", "meant", "media", "metal",
    "midst", "minor", "minus", "mixed", "model", "money", "month", "moral", "motor", "mount",
    "mouse", "mouth", "movie", "music", "needs", "never", "newly", "night", "noise", "north",
    "noted", "novel", "nurse", "occur", "ocean", "offer", "often", "order", "other", "ought",
    "paint", "panel", "paper", "party", "peace", "peter", "phase", "phone", "photo", "piece",
    "pilot", "pitch", "place", "plain", "plane", "plant", "plate", "point", "pound", "power",
    "press", "price", "pride", "prime", "print", "prior", "prize", "proof", "proud", "prove",
    "queen", "quick", "quiet", "quite", "radio", "raise", "range", "rapid", "ratio", "reach",
    "ready", "refer", "right", "rival", "river", "robin", "roger", "roman", "rough", "round",
    "route", "royal", "rural", "scale", "scene", "scope", "score", "sense", "serve", "seven",
    "shall", "shape", "share", "sharp", "sheet", "shelf", "shell", "shift", "shirt", "shock",
    "shoot", "short", "shown", "shift", "sight", "since", "sixth", "sixty", "sized", "skill",
    "sleep", "slide", "small", "smart", "smile", "smith", "smoke", "solid", "solve", "sorry",
    "sound", "south", "space", "spare", "speak", "speed", "spend", "spent", "split", "spoke",
    "sport", "staff", "stage", "stake", "stand", "start", "state", "steam", "steel", "stick",
    "still", "stock", "stone", "stood", "store", "storm", "story", "strip", "stuck", "study",
    "stuff", "style", "sugar", "suite", "super", "sweet", "table", "taken", "taste", "taxes",
    "teach", "teeth", "terry", "texas", "thank", "theft", "their", "theme", "there", "these",
    "thick", "thing", "think", "third", "those", "three", "threw", "throw", "tight", "times",
    "tired", "title", "today", "topic", "total", "touch", "tough", "tower", "track", "trade",
    "train", "treat", "trend", "trial", "tried", "tries", "truck", "truly", "trust", "truth",
    "twice", "under", "union", "unity", "until", "upper", "upset", "urban", "usage", "usual",
    "valid", "value", "video", "virus", "visit", "vital", "voice", "waste", "watch", "water",
    "weigh", "weird", "where", "which", "while", "white", "whole", "whose", "woman", "women",
    "world", "worry", "worse", "worst", "worth", "would", "wound", "write", "wrong", "wrote",
    "yield", "young", "youth"
)


val categoriesWithWords = mapOf(
    "Food" to listOf(
        "apple", "banana", "carrot", "bread", "cheese", "pasta", "salad", "pizza", "burger", "rice",
        "noodles", "pancake", "soup", "fries", "steak", "taco", "burrito", "curry", "sushi", "toast",
        "muffin", "cookie", "pie", "donut", "sandwich", "waffle", "omelet", "chili", "dumpling", "sausage",
        "kebab", "lasagna", "risotto", "bagel", "quiche", "shawarma", "meatball", "pudding", "falafel", "salmon",
        "beef", "chicken", "lamb", "pork", "lobster", "shrimp", "squid", "caviar", "tofu", "tempeh",
        "lentils", "beans", "corn", "broccoli", "spinach", "cauliflower", "eggplant", "zucchini", "cabbage", "radish",
        "beetroot", "pumpkin", "potato", "sweet potato", "peas", "okra", "mushroom", "artichoke", "asparagus", "celery",
        "garlic", "onion", "tomato", "lettuce", "parsley", "basil", "cilantro", "sage", "thyme", "rosemary",
        "ginger", "chili pepper", "paprika", "mustard", "horseradish", "mayonnaise", "ketchup", "barbecue sauce", "hot sauce", "soy sauce",
        "olive oil", "butter", "margarine", "vinegar", "yeast", "jelly", "honey", "jam", "sugar", "chocolate"
    ),
    "Drinks" to listOf(
        "water", "juice", "soda", "tea", "coffee", "milk", "smoothie", "lemonade", "cola", "fizzy water",
        "beer", "wine", "champagne", "whiskey", "vodka", "rum", "gin", "brandy", "cider", "espresso",
        "latte", "cappuccino", "mocha", "frappe", "hot chocolate", "matcha", "chai", "green tea", "black tea", "oolong tea",
        "herbal tea", "iced tea", "milkshake", "strawberry shake", "mango shake", "protein shake", "energy drink", "tonic water", "ginger ale", "root beer",
        "mineral water", "sparkling water", "juice box", "orange juice", "apple juice", "grape juice", "cranberry juice", "pineapple juice", "tomato juice", "coconut water",
        "soy milk", "almond milk", "rice milk", "cashew milk", "oat milk", "peppermint tea", "hibiscus tea", "ginger tea", "turmeric tea", "kombucha",
        "cold brew", "americano", "flat white", "macchiato", "affogato", "nitro cold brew", "turmeric latte", "bubble tea", "jasmine tea", "barley tea",
        "beer shandy", "bloody mary", "margarita", "sangria", "martini", "cosmopolitan", "negroni", "daiquiri", "pina colada", "tequila sunrise",
        "mai tai", "long island iced tea", "mocktail", "cocoa", "mulled wine", "buttermilk", "kefir", "lassi", "sherbet", "switchel"
    ),
    "Fruits" to listOf(
        "mango", "orange", "grape", "peach", "apple", "banana", "kiwi", "papaya", "pineapple", "watermelon",
        "cantaloupe", "honeydew", "cherry", "plum", "pear", "pomegranate", "fig", "guava", "apricot", "lime",
        "lemon", "coconut", "lychee", "jackfruit", "durian", "dragon fruit", "starfruit", "passionfruit", "persimmon", "avocado",
        "blackberry", "blueberry", "raspberry", "strawberry", "cranberry", "mulberry", "elderberry", "goji berry", "boysenberry", "cloudberry",
        "currant", "marionberry", "grapefruit", "soursop", "tangerine", "clementine", "mandarin", "nectarine", "olive", "date",
        "quince", "loquat", "salak", "santol", "rambutan", "longan", "sugar apple", "custard apple", "sapodilla", "kiwano",
        "ugli fruit", "finger lime", "buddha's hand", "satsuma", "jabuticaba", "cherimoya", "acerola", "noni", "pili nut", "pecan",
        "walnut", "hazelnut", "chestnut", "cashew", "pistachio", "macadamia", "almond", "acai", "black sapote", "white sapote",
        "spondias", "tamarind", "mamoncillo", "caimito", "mangosteen", "feijoa", "horned melon", "medlar", "jambul", "surinam cherry"
    ),
    "Names" to listOf(
        "John", "Alice", "Sam", "Emma", "Michael", "Sarah", "David", "Olivia", "Chris", "Sophie",
        "James", "Emily", "Daniel", "Jessica", "Robert", "Hannah", "Paul", "Megan", "Kevin", "Grace",
        "Thomas", "Lucy", "Jason", "Rachel", "George", "Chloe", "Richard", "Mia", "Joseph", "Sophia",
        "Charles", "Ella", "Brian", "Anna", "Edward", "Lily", "Henry", "Maya", "Steven", "Ruby",
        "Matthew", "Emma", "Anthony", "Aria", "Mark", "Isla", "Donald", "Alice", "Scott", "Luna",
        "Patrick", "Zara", "William", "Leah", "Andrew", "Mila", "Benjamin", "Layla", "Nicholas", "Nora",
        "Adam", "Elena", "Harry", "Eva", "Alex", "Bella", "Justin", "Zoey", "Frank", "Ava",
        "Ethan", "Ivy", "Peter", "Aurora", "Louis", "Poppy", "Jacob", "Hazel", "Zachary", "Sadie",
        "Luke", "Willow", "Jonathan", "Ellie", "Simon", "Violet", "Caleb", "Sienna", "Martin", "Rose"
    ),
    "Animals" to listOf(
        "lion", "tiger", "elephant", "giraffe", "zebra", "kangaroo", "panda", "bear", "wolf", "fox",
        "deer", "monkey", "rabbit", "squirrel", "snake", "eagle", "hawk", "dolphin", "whale", "shark",
        "penguin", "seal", "octopus", "crab", "turtle", "flamingo", "peacock", "ostrich", "crocodile", "alligator",
        "bat", "rat", "mouse", "hamster", "guinea pig", "ferret", "hedgehog", "chinchilla", "parrot", "canary",
        "goldfish", "betta", "tropical fish", "frog", "toad", "salamander", "newt", "komodo dragon", "rhinoceros", "hippopotamus",
        "antelope", "buffalo", "bison", "lynx", "cougar", "jaguar", "cheetah", "seal", "sea lion", "manatee",
        "walrus", "platypus", "koala", "sloth", "armadillo", "anteater", "capybara", "narwhal", "oryx", "wolverine",
        "impala", "gazelle", "kangaroo rat", "quokka", "lemur", "tamarin", "orangutan", "gorilla", "chimpanzee", "bonobo",
        "golden retriever", "labrador", "poodle", "bulldog", "beagle", "shepherd", "terrier", "dalmatian", "corgi", "great dane",
        "sphynx", "bengal", "siamese", "persian", "russian blue", "chow", "pug", "shih tzu", "golden hamster", "hedgehog"
    ),
    "Colors" to listOf(
        "red", "blue", "green", "yellow", "orange", "purple", "pink", "black", "white", "gray",
        "brown", "cyan", "magenta", "violet", "indigo", "gold", "silver", "beige", "turquoise", "teal",
        "crimson", "navy", "lavender", "peach", "mint", "coral", "emerald", "amber", "ruby", "sapphire",
        "topaz", "onyx", "ivory", "charcoal", "plum", "salmon", "tan", "chocolate", "seafoam", "khaki",
        "mustard", "auburn", "fuchsia", "burgundy", "periwinkle", "rose", "cobalt", "chartreuse", "olive", "mahogany",
        "cerulean", "blush", "apple green", "electric blue", "jet", "melon", "mauve", "tangerine", "eggplant", "sienna",
        "fawn", "carnation", "cerise", "lavender", "sepia", "zinnia", "vanilla", "sage", "dandelion", "flame",
        "raspberry", "pearl", "moss", "cocoa", "copper", "sand", "steel", "chiffon", "cornflower", "wheat",
        "cherry", "cantaloupe", "fuchsia", "cream", "sunset", "cypress", "heather", "forest", "pansy", "basil",
        "pine", "apricot", "mink", "tawny", "blush", "emerald", "sky", "lavender", "goldenrod", "antique"
    ),
    "Countries" to listOf(
        "USA", "Canada", "Mexico", "Brazil", "Argentina", "UK", "France", "Germany", "Spain", "Italy",
        "Russia", "China", "Japan", "India", "Australia", "South Africa", "Egypt", "Saudi Arabia", "Turkey", "Greece",
        "Netherlands", "Belgium", "Sweden", "Norway", "Finland", "Denmark", "Ireland", "Portugal", "Switzerland", "Austria",
        "Czech Republic", "Hungary", "Poland", "Romania", "Ukraine", "Vietnam", "Indonesia", "Thailand", "Philippines", "Malaysia",
        "Singapore", "South Korea", "New Zealand", "Israel", "Saudi Arabia", "United Arab Emirates", "Pakistan", "Bangladesh", "Sri Lanka", "Nepal",
        "Afghanistan", "Iraq", "Iran", "Jordan", "Kuwait", "Qatar", "Bahrain", "Oman", "Syria", "Yemen",
        "Chile", "Colombia", "Peru", "Venezuela", "Ecuador", "Bolivia", "Paraguay", "Uruguay", "Costa Rica", "Panama",
        "Cuba", "Dominican Republic", "Haiti", "Jamaica", "Barbados", "Trinidad", "Saint Lucia", "Saint Vincent", "Bahamas", "Belize",
        "Honduras", "Guatemala", "El Salvador", "Nicaragua", "Puerto Rico", "Fiji", "Tonga", "Samoa", "Papua New Guinea", "Solomon Islands",
        "Malawi", "Zambia", "Zimbabwe", "Botswana", "Namibia", "Angola", "Tanzania", "Kenya", "Uganda", "Rwanda",
        "South Sudan", "Ethiopia", "Somalia", "Cameroon", "Nigeria", "Ghana", "Senegal", "Mali", "Ivory Coast", "Togo"
    ),
    "Sports" to listOf(
        "soccer", "basketball", "baseball", "tennis", "cricket", "hockey", "golf", "rugby", "volleyball", "swimming",
        "running", "cycling", "boxing", "wrestling", "table tennis", "badminton", "football", "gymnastics", "karate", "taekwondo",
        "fencing", "archery", "skateboarding", "snowboarding", "skiing", "surfing", "diving", "rock climbing", "mountaineering", "hiking",
        "weightlifting", "powerlifting", "crossfit", "cheerleading", "dance", "martial arts", "sailing", "rowing", "kayaking", "paddleboarding",
        "billiards", "darts", "poker", "eSports", "motorsport", "formula one", "NASCAR", "cycling", "triathlon", "pentathlon",
        "decathlon", "marathon", "ultramarathon", "skating", "curling", "bobsleigh", "luge", "skeleton", "figure skating", "speed skating",
        "ice fishing", "airsoft", "paintball", "hunting", "fishing", "equestrian", "dressage", "rodeo", "bull riding", "car racing",
        "atv racing", "indoor skydiving", "yoga", "pilates", "spinning", "cross-country skiing", "snowshoeing", "lumberjack", "robbing", "parkour",
        "Zumba", "cheerleading", "synchronized swimming", "dragon boat racing", "kite surfing", "windsurfing", "surf lifesaving", "bodyboarding", "aerobics", "belly dancing"
    ),
    "Seasons" to listOf(
        "winter", "spring", "summer", "autumn", "fall", "monsoon", "dry season", "wet season", "hurricane season", "holiday season",
        "rainy season", "blooming season", "festive season", "growing season", "harvest season", "frost season", "mating season", "hiking season", "ski season", "fishing season",
        "hunting season", "wildflower season", "migration season", "fruiting season", "shedding season", "hibernation season", "surf season", "barbecue season", "storm season", "sunshine season",
        "gale season", "flood season", "hurricane season", "drying season", "drainage season", "dewy season", "crisp season", "refreshing season", "sizzling season", "baking season",
        "frosty season", "chilly season", "sunny season", "overcast season", "balmy season", "humid season", "stormy season", "sweater weather", "tropical season", "clement season",
        "vibrant season", "colorful season", "peppy season", "fruity season", "breezy season", "cloudy season", "crisp autumn", "golden autumn", "colorful spring", "fresh spring",
        "scorching summer", "hot summer", "mild winter", "snowy winter", "cool fall", "colorful fall", "warm autumn", "transitional season", "tender spring", "gentle spring"
    ),
    "Occupations" to listOf(
        "doctor", "engineer", "teacher", "nurse", "chef", "driver", "artist", "musician", "writer", "scientist",
        "lawyer", "accountant", "police", "firefighter", "soldier", "journalist", "architect", "plumber", "electrician", "mechanic",
        "manager", "director", "programmer", "analyst", "technician", "salesperson", "receptionist", "waiter", "hairdresser", "builder",
        "researcher", "farmer", "fisherman", "pilot", "entrepreneur", "consultant", "nanny", "cleaner", "guard", "cashier",
        "barista", "waitress", "broker", "designer", "developer", "executive", "trainer", "therapist", "pharmacist", "optician",
        "veterinarian", "account manager", "HR specialist", "data scientist", "social worker", "trader", "biochemist", "physicist", "mathematician", "geologist",
        "anthropologist", "psychologist", "linguist", "sociologist", "ecologist", "statistician", "historian", "zoologist", "biologist", "astrophysicist",
        "environmentalist", "neuroscientist", "nuclear engineer", "surgical technician", "radiologic technologist", "physical therapist", "occupational therapist", "clinical psychologist", "graphic designer", "web developer",
        "IT support", "content creator", "social media manager", "digital marketer", "real estate agent", "business analyst", "project manager", "supply chain manager", "production manager", "quality control inspector"
    )
)

